<?php

namespace App\Filament\Actions\Story;

use App\Filament\Resources\StoryResource\Pages\ListStories;
use App\Models\Category;
use App\Models\Story;
use App\Models\StorySeries;
use Filament\Actions\Concerns\CanCustomizeProcess;
use Filament\Forms\Components\Select;
use Filament\Notifications\Notification;
use Filament\Tables\Actions\BulkAction;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;

class AttachToStorySeriesBulkAction extends BulkAction
{
    use CanCustomizeProcess;

    public static function getDefaultName(): ?string
    {
        return 'attach_series_to_stories'; // TODO: Change the autogenerated stub
    }

    public function getPluralModelLabel(): string
    {
        return "Attach to Series";
    }

    protected function setUp(): void
    {
        parent::setUp();

        $this->label("Attach to Series");
        $this->color("success");
        $this->icon('heroicon-o-paper-clip');

        $this->requiresConfirmation();
        $this->modalHeading("Attach Stories to a Series");
        $this->modalButton("Attach");

        $this->successNotification(
            Notification::make()
                ->success()
                ->title("Attached to Series")
                ->body("Stories have been attached to the series.")
        );

        $this->form([
            Select::make('series')
                ->options(
                    function () {
                        return StorySeries::query()->pluck('title', 'id');
                    }
                )
                ->placeholder("Select Series")
                ->searchable()
                ->required()
        ]);

        $this->action(function (): void {
            $this->process(function (Collection $records, array $data): void {
                $records->each(
                    function (Story $story) use ($data) {
                        $story->update(['story_series_id' => $data['series']]);
                    }
                );
            });

            $this->success();
        });

        $this->deselectRecordsAfterCompletion();
    }
}
